version: '3'

services:
  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: apigateway
      POSTGRES_PASSWORD: apigateway
    volumes:
      - apigateway-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: ["postgres", "-c" , "log_statement=all"]

volumes:
  apigateway-db: {}